// web/src/routes/prejoin.tsx
import { useNavigate } from "@solidjs/router";
import { Component, createSignal, Show } from "solid-js";
import { useSearchParams } from "solid-start";

import { Button } from "../components/button/button";
import { Toggle } from "../components/toggle/toggle";
import { apiV1Url } from "../config";
import { UseRootContext } from "~/common/root.state";

import "./prejoin.css";
import { Header } from "~/components/header/header";
const PrejoinForm: Component = () => {
  const navigate = useNavigate();
  const [{ isSpectator, roomId, username }, { setIsSpectator, setRoomId, setUsername }] = UseRootContext();
  const [params] = useSearchParams<{ create: string; }>();
  const isCreatingRoom = Boolean(params.create);
  const title = isCreatingRoom ? "Create a New Room" : "Joining Room";
  const buttonText = isCreatingRoom ? "create room" : "join room";
  const [usernameError, setUsernameError] = createSignal<string | null>(null);
  const handleInputChanged = (event: KeyboardEvent) => {
    try {
      // @ts-ignore
      const username: string = event?.target?.value;
      if (username.length > 12) {
        setUsernameError("Username must be less than 12 characters");
        return;
      }
      setUsernameError(null);
      setUsername(username);
    } catch (e) {
      console.error(e);
    }
  };
  async function createRoom() {
    const createRoomUrl = apiV1Url + "/createRoom";
    const response = await fetch(createRoomUrl, {
      method: "POST",
    });
    const data = await response.text();
    setRoomId(data);
    navigate(`/room/${roomId()}`);
  }
  return (
    <>
      <Header />
      <div class="prejoin-form">
        <h2>{title}</h2>
        <div class="input-wrapper">
          <label for="username">Username</label>
          <input
            data-testid="username-input"
            type="text"
            name="username"
            onKeyUp={handleInputChanged}
            value={username()}
          />
          <Show when={usernameError()}>
            <span class="error">{usernameError()}</span>
          </Show>
        </div>
        <div class="is-spectator">
          <div class="is-spectator-switch">
            <Toggle
              name="isSpectator"
              checked={isSpectator()}
              label="Join as Spectator"
              action={() => setIsSpectator((v) => !v)}
            ></Toggle>
          </div>
          <span id="change-later">You can change this later</span>
        </div>
        <Button
          testId="create-room"
          disabled={!!usernameError()}
          action={async () =>
            isCreatingRoom ? await createRoom() : navigate(`/room/${roomId()}`)
          }
        >
          <span>{buttonText}</span>
        </Button>
      </div>
    </>
  );
};
export default PrejoinForm;

// web/src/pages/prejoin/index.tsx
import { RootContext, RootDispatchContext } from "@/common/root.context";
import { useRouter } from "next/router";
import { useContext, useEffect, useState } from "react";
import { Button } from "../../components/button/button";
import { Toggle } from "../../components/toggle/toggle";
import { apiV1Url } from "../../config";
import styles from "./index.module.css";
const PrejoinForm = () => {
  const router = useRouter();
  const { username, isSpectator, roomId } = useContext(RootContext);
  const dispatch = useContext(RootDispatchContext);
  const { create } = router.query;
  const isCreatingRoom = Boolean(create);
  const title = isCreatingRoom ? "Create a New Room" : "Joining Room";
  const buttonText = isCreatingRoom ? "create room" : "join room";
  const [usernameError, setUsernameError] = useState<string | null>(null);
  const handleInputChanged = (event: unknown) => {
    try {
      // @ts-ignore
      const username: string = event?.target?.value;
      if (username.length > 12) {
        setUsernameError("Username must be less than 12 characters");
        return;
      }
      setUsernameError(null);
      dispatch({ type: 'setUsername', payload: username });
    } catch (e) {
      console.error(e);
    }
  };
  async function createRoom() {
    const createRoomUrl = apiV1Url + "/createRoom";
    const response = await fetch(createRoomUrl, {
      method: "POST",
    });
    const data = await response.text();
    console.log(data);
    dispatch({ type: 'setRoomId', payload: data });
    router.replace(`/room/${data}`);
  }
  return (
    <div className={styles.prejoinForm}>
      <h2>{title}</h2>
      <div className={styles.inputWrapper}>
        <label htmlFor="username">Username</label>
        <input
          data-testid="username-input"
          type="text"
          name="username"
          onKeyUp={handleInputChanged}
          onChange={handleInputChanged}
          value={username}
        />
        {usernameError && (
          <span className={styles.error}>{usernameError}</span>
        )}
      </div>
      <div className={styles.isSpectator}>
        <div className={styles.isSpectatorSwitch}>
          <Toggle
            name="isSpectator"
            checked={isSpectator}
            label="Join as Spectator"
            action={() => dispatch({ type: 'setIsSpectator' })}
          ></Toggle>
        </div>
        <span id={styles["change-later"]}>You can change this later</span>
      </div>
      <Button
        testId="create-room"
        disabled={!!usernameError}
        action={async () =>
          isCreatingRoom ? await createRoom() : router.push(`/room/${roomId}`)
        }
      >
        <span>{buttonText}</span>
      </Button>
    </div >
  );
};
export default PrejoinForm;
